// Package entities
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package entities

import (
	"time"
)

var _ = time.Time{}

// Org ENGINE InnoDB CHARSET utf8mb4 COMMENT '组织'
type Org struct {
	Id              uint64     `gorm:"column:id;primaryKey" json:"id"`                    // ID
	OrgUuid         string     `gorm:"column:org_uuid" json:"org_uuid"`                   // uuid
	CreatedTime     time.Time  `gorm:"column:created_time" json:"created_time"`           // 创建时间
	UpdatedTime     time.Time  `gorm:"column:updated_time" json:"updated_time"`           // 最后修改时间
	DeletedTime     *time.Time `gorm:"column:deleted_time" json:"deleted_time"`           // 删除时间
	IsDeleted       bool       `gorm:"column:is_deleted" json:"is_deleted"`               // 是否已删除
	OrgEmail        string     `gorm:"column:org_email" json:"org_email"`                 // 邮箱
	OrgName         string     `gorm:"column:org_name" json:"org_name"`                   // 名称
	OrgLogo         string     `gorm:"column:org_logo" json:"org_logo"`                   // logo
	OrgStatus       string     `gorm:"column:org_status" json:"org_status"`               // 状态
	ActiveBeginTime *time.Time `gorm:"column:active_begin_time" json:"active_begin_time"` // 激活开始时间
	ActiveEndTime   *time.Time `gorm:"column:active_end_time" json:"active_end_time"`     // 激活结束时间
	DisableTime     *time.Time `gorm:"column:disable_time" json:"disable_time"`           // 禁用时间
	BlacklistTime   *time.Time `gorm:"column:blacklist_time" json:"blacklist_time"`       // 黑名单时间
	PasswordHash    string     `gorm:"column:password_hash" json:"password_hash"`         // 密码
}

// TableName table name
func (s *Org) TableName() string {
	return "srv_org"
}
