// Package datas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package datas

import (
	"bytes"
	context "context"
	gormutil "github.com/ikaiguang/go-srv-kit/data/gorm"
	gorm "gorm.io/gorm"
	"strings"

	entities "github.com/ikaiguang/go-srv-user/internal/domain/entity/user"
	repos "github.com/ikaiguang/go-srv-user/internal/domain/repo/user"
	schemas "github.com/ikaiguang/go-srv-user/internal/infra/mysql/schema/user"
)

// userRepo repo
type userRepo struct {
	dbConn     *gorm.DB     // *gorm.DB
	UserSchema schemas.User // User
}

// NewUserRepo new data repo
func NewUserRepo(dbConn *gorm.DB) repos.UserRepo {
	return &userRepo{
		dbConn: dbConn,
	}
}

// =============== 创建 ===============

// create insert one
func (s *userRepo) create(ctx context.Context, dbConn *gorm.DB, dataModel *entities.User) (err error) {
	err = dbConn.WithContext(ctx).Create(dataModel).Error
	if err != nil {
		return err
	}
	return
}

// Create insert one
func (s *userRepo) Create(ctx context.Context, dataModel *entities.User) error {
	return s.create(ctx, s.dbConn, dataModel)
}

// CreateWithDBConn create
func (s *userRepo) CreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.User) error {
	return s.create(ctx, dbConn, dataModel)
}

// existCreate exist create
func (s *userRepo) existCreate(ctx context.Context, dbConn *gorm.DB, dataModel *entities.User) (anotherModel *entities.User, isNotFound bool, err error) {
	anotherModel = new(entities.User)
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		Where("id = ?", dataModel.Id).
		First(anotherModel).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			isNotFound = true
			err = nil
		}
		return
	}
	return
}

// ExistCreate exist create
func (s *userRepo) ExistCreate(ctx context.Context, dataModel *entities.User) (anotherModel *entities.User, isNotFound bool, err error) {
	return s.existCreate(ctx, s.dbConn, dataModel)
}

// ExistCreateWithDBConn exist create
func (s *userRepo) ExistCreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.User) (anotherModel *entities.User, isNotFound bool, err error) {
	return s.existCreate(ctx, dbConn, dataModel)
}

// createInBatches create many
func (s *userRepo) createInBatches(ctx context.Context, dbConn *gorm.DB, dataModels []*entities.User, batchSize int) (err error) {
	err = dbConn.WithContext(ctx).CreateInBatches(dataModels, batchSize).Error
	if err != nil {
		return err
	}
	return
}

// CreateInBatches create many
func (s *userRepo) CreateInBatches(ctx context.Context, dataModels []*entities.User, batchSize int) error {
	return s.createInBatches(ctx, s.dbConn, dataModels, batchSize)
}

// CreateInBatchesWithDBConn create many
func (s *userRepo) CreateInBatchesWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*entities.User, batchSize int) error {
	return s.createInBatches(ctx, dbConn, dataModels, batchSize)
}

// =============== 更新 ===============

// update update
func (s *userRepo) update(ctx context.Context, dbConn *gorm.DB, dataModel *entities.User) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		Where("id = ?", dataModel.Id).
		Save(dataModel).Error
	if err != nil {
		return err
	}
	return
}

// Update update
func (s *userRepo) Update(ctx context.Context, dataModel *entities.User) error {
	return s.update(ctx, s.dbConn, dataModel)
}

// UpdateWithDBConn update
func (s *userRepo) UpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.User) error {
	return s.update(ctx, dbConn, dataModel)
}

// existUpdate exist update
func (s *userRepo) existUpdate(ctx context.Context, dbConn *gorm.DB, dataModel *entities.User) (anotherModel *entities.User, isNotFound bool, err error) {
	anotherModel = new(entities.User)
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		Where("id = ?", dataModel.Id).
		Where("id != ?", dataModel.Id).
		First(anotherModel).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			isNotFound = true
			err = nil
		}
		return
	}
	return
}

// ExistUpdate exist update
func (s *userRepo) ExistUpdate(ctx context.Context, dataModel *entities.User) (anotherModel *entities.User, isNotFound bool, err error) {
	return s.existUpdate(ctx, s.dbConn, dataModel)
}

// ExistUpdateWithDBConn exist update
func (s *userRepo) ExistUpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.User) (anotherModel *entities.User, isNotFound bool, err error) {
	return s.existUpdate(ctx, dbConn, dataModel)
}

// =============== query one : 查一个 ===============

// queryOneById query one by id
func (s *userRepo) queryOneById(ctx context.Context, dbConn *gorm.DB, id interface{}) (dataModel *entities.User, isNotFound bool, err error) {
	dataModel = new(entities.User)
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		Where("id = ?", id).
		First(dataModel).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			err = nil
			isNotFound = true
		}
		return
	}
	return
}

// QueryOneById query one by id
func (s *userRepo) QueryOneById(ctx context.Context, id interface{}) (dataModel *entities.User, isNotFound bool, err error) {
	return s.queryOneById(ctx, s.dbConn, id)
}

// QueryOneByIdWithDBConn query one by id
func (s *userRepo) QueryOneByIdWithDBConn(ctx context.Context, dbConn *gorm.DB, id interface{}) (dataModel *entities.User, isNotFound bool, err error) {
	return s.queryOneById(ctx, dbConn, id)
}

// queryOneByConditions query one by conditions
func (s *userRepo) queryOneByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *entities.User, isNotFound bool, err error) {
	dataModel = new(entities.User)
	dbConn = dbConn.WithContext(ctx).Table(s.UserSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		First(dataModel).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			err = nil
			isNotFound = true
		}
		return
	}
	return
}

// QueryOneByConditions query one by conditions
func (s *userRepo) QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *entities.User, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, s.dbConn, conditions)
}

// QueryOneByConditionsWithDBConn query one by conditions
func (s *userRepo) QueryOneByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *entities.User, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, dbConn, conditions)
}

// =============== query all : 查全部 ===============

// queryAllByConditions query all by conditions
func (s *userRepo) queryAllByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModels []*entities.User, err error) {
	dbConn = dbConn.WithContext(ctx).Table(s.UserSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		Find(&dataModels).Error
	if err != nil {
		return dataModels, err
	}
	return
}

// QueryAllByConditions query all by conditions
func (s *userRepo) QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) ([]*entities.User, error) {
	return s.queryAllByConditions(ctx, s.dbConn, conditions)
}

// QueryAllByConditionsWithDBConn query all by conditions
func (s *userRepo) QueryAllByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) ([]*entities.User, error) {
	return s.queryAllByConditions(ctx, dbConn, conditions)
}

// =============== list : 列表 ===============

// list 列表
func (s *userRepo) list(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormutil.PaginatorArgs) (dataModels []*entities.User, recordCount int64, err error) {
	// query where
	dbConn = dbConn.WithContext(ctx).Table(s.UserSchema.TableName())
	dbConn = s.WhereConditions(dbConn, conditions)
	dbConn = gormutil.AssembleWheres(dbConn, paginatorArgs.PageWheres)

	err = dbConn.Count(&recordCount).Error
	if err != nil {
		return
	} else if recordCount == 0 {
		return // empty
	}

	// pagination
	dbConn = gormutil.AssembleOrders(dbConn, paginatorArgs.PageOrders)
	err = gormutil.Paginator(dbConn, paginatorArgs.PageOption).
		Find(&dataModels).Error
	if err != nil {
		return
	}
	return
}

// List 列表
func (s *userRepo) List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormutil.PaginatorArgs) ([]*entities.User, int64, error) {
	return s.list(ctx, s.dbConn, conditions, paginatorArgs)
}

// ListWithDBConn 列表
func (s *userRepo) ListWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormutil.PaginatorArgs) ([]*entities.User, int64, error) {
	return s.list(ctx, dbConn, conditions, paginatorArgs)
}

// =============== delete : 删除 ===============

// delete delete one
func (s *userRepo) delete(ctx context.Context, dbConn *gorm.DB, dataModel *entities.User) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		Where("id = ?", dataModel.Id).
		Delete(dataModel).Error
	if err != nil {
		return err
	}
	return
}

// Delete delete one
func (s *userRepo) Delete(ctx context.Context, dataModel *entities.User) error {
	return s.delete(ctx, s.dbConn, dataModel)
}

// DeleteWithDBConn delete one
func (s *userRepo) DeleteWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.User) error {
	return s.delete(ctx, dbConn, dataModel)
}

// deleteByIds delete by ids
func (s *userRepo) deleteByIds(ctx context.Context, dbConn *gorm.DB, ids interface{}) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		Where("id in (?)", ids).
		Delete(entities.User{}).Error
	if err != nil {
		return err
	}
	return
}

// DeleteByIds delete by ids
func (s *userRepo) DeleteByIds(ctx context.Context, ids interface{}) error {
	return s.deleteByIds(ctx, s.dbConn, ids)
}

// DeleteByIdsWithDBConn delete by ids
func (s *userRepo) DeleteByIdsWithDBConn(ctx context.Context, dbConn *gorm.DB, ids interface{}) error {
	return s.deleteByIds(ctx, dbConn, ids)
}

// =============== insert : 批量入库 ===============

var _ gormutil.BatchInsertRepo = new(UserSlice)

// UserSlice 表切片
type UserSlice []*entities.User

// TableName 表名
func (s *UserSlice) TableName() string {
	if len(*s) > 0 {
		return (*s)[0].TableName()
	}
	return (&entities.User{}).TableName()
}

// Len 长度
func (s *UserSlice) Len() int {
	return len(*s)
}

// InsertColumns 批量入库的列
func (s *UserSlice) InsertColumns() (columnList []string, placeholder string) {
	// columns
	columnList = []string{
		"user_uuid", "created_time", "updated_time", "deleted_time", "is_deleted", "user_email",
		"user_nickname", "user_avatar", "user_gender", "user_status", "active_begin_time", "active_end_time",
		"disable_time", "blacklist_time", "password_hash",
	}

	// placeholders
	insertPlaceholderBytes := bytes.Repeat([]byte("?, "), len(columnList))
	insertPlaceholderBytes = bytes.TrimSuffix(insertPlaceholderBytes, []byte(", "))

	return columnList, string(insertPlaceholderBytes)
}

// InsertValues 批量入库的值
func (s *UserSlice) InsertValues(args *gormutil.BatchInsertValueArgs) (prepareData []interface{}, placeholderSlice []string) {
	dataModels := (*s)[args.StepStart:args.StepEnd]
	for index := range dataModels {
		// placeholder
		placeholderSlice = append(placeholderSlice, "("+args.InsertPlaceholder+")")

		// prepare data
		prepareData = append(prepareData, dataModels[index].UserUuid)
		prepareData = append(prepareData, dataModels[index].CreatedTime)
		prepareData = append(prepareData, dataModels[index].UpdatedTime)
		prepareData = append(prepareData, dataModels[index].DeletedTime)
		prepareData = append(prepareData, dataModels[index].IsDeleted)
		prepareData = append(prepareData, dataModels[index].UserEmail)
		prepareData = append(prepareData, dataModels[index].UserNickname)
		prepareData = append(prepareData, dataModels[index].UserAvatar)
		prepareData = append(prepareData, dataModels[index].UserGender)
		prepareData = append(prepareData, dataModels[index].UserStatus)
		prepareData = append(prepareData, dataModels[index].ActiveBeginTime)
		prepareData = append(prepareData, dataModels[index].ActiveEndTime)
		prepareData = append(prepareData, dataModels[index].DisableTime)
		prepareData = append(prepareData, dataModels[index].BlacklistTime)
		prepareData = append(prepareData, dataModels[index].PasswordHash)
	}
	return prepareData, placeholderSlice
}

// UpdateColumns 批量入库的列
func (s *UserSlice) UpdateColumns() (columnList []string) {
	// columns
	columnList = []string{
		"user_uuid=excluded.user_uuid", "created_time=excluded.created_time", "updated_time=excluded.updated_time",
		"deleted_time=excluded.deleted_time", "is_deleted=excluded.is_deleted", "user_email=excluded.user_email",
		"user_nickname=excluded.user_nickname", "user_avatar=excluded.user_avatar", "user_gender=excluded.user_gender",
		"user_status=excluded.user_status", "active_begin_time=excluded.active_begin_time", "active_end_time=excluded.active_end_time",
		"disable_time=excluded.disable_time", "blacklist_time=excluded.blacklist_time", "password_hash=excluded.password_hash",
	}
	return columnList
}

// ConflictActionForMySQL 更新冲突时的操作
func (s *UserSlice) ConflictActionForMySQL() (req *gormutil.BatchInsertConflictActionReq) {
	req = &gormutil.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "AS excluded",
		OnConflictTarget:      "ON DUPLICATE KEY",
		OnConflictAction:      "UPDATE " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// ConflictActionForPostgres 更新冲突时的操作
func (s *UserSlice) ConflictActionForPostgres() (req *gormutil.BatchInsertConflictActionReq) {
	req = &gormutil.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "",
		OnConflictTarget:      "ON CONFLICT(id)",
		OnConflictAction:      "DO UPDATE SET " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// insert 批量插入
func (s *userRepo) insert(ctx context.Context, dbConn *gorm.DB, dataModels UserSlice) error {
	return gormutil.BatchInsertWithContext(ctx, dbConn, &dataModels)
}

// Insert 批量插入
func (s *userRepo) Insert(ctx context.Context, dataModels []*entities.User) error {
	return s.insert(ctx, s.dbConn, dataModels)
}

// InsertWithDBConn 批量插入
func (s *userRepo) InsertWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*entities.User) error {
	return s.insert(ctx, dbConn, dataModels)
}

// =============== conditions : 条件 ===============

// WhereConditions orm where
func (s *userRepo) WhereConditions(dbConn *gorm.DB, conditions map[string]interface{}) *gorm.DB {

	// table name
	//tableName := s.UserSchema.TableName()

	// On-demand loading

	// id
	//if data, ok := conditions["id"]; ok {
	//	dbConn = dbConn.Where(tableName+".id = ?", data)
	//}

	// user_uuid
	//if data, ok := conditions["user_uuid"]; ok {
	//	dbConn = dbConn.Where(tableName+".user_uuid = ?", data)
	//}

	// created_time
	//if data, ok := conditions["created_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".created_time = ?", data)
	//}

	// updated_time
	//if data, ok := conditions["updated_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".updated_time = ?", data)
	//}

	// deleted_time
	//if data, ok := conditions["deleted_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".deleted_time = ?", data)
	//}

	// is_deleted
	//if data, ok := conditions["is_deleted"]; ok {
	//	dbConn = dbConn.Where(tableName+".is_deleted = ?", data)
	//}

	// user_email
	//if data, ok := conditions["user_email"]; ok {
	//	dbConn = dbConn.Where(tableName+".user_email = ?", data)
	//}

	// user_nickname
	//if data, ok := conditions["user_nickname"]; ok {
	//	dbConn = dbConn.Where(tableName+".user_nickname = ?", data)
	//}

	// user_avatar
	//if data, ok := conditions["user_avatar"]; ok {
	//	dbConn = dbConn.Where(tableName+".user_avatar = ?", data)
	//}

	// user_gender
	//if data, ok := conditions["user_gender"]; ok {
	//	dbConn = dbConn.Where(tableName+".user_gender = ?", data)
	//}

	// user_status
	//if data, ok := conditions["user_status"]; ok {
	//	dbConn = dbConn.Where(tableName+".user_status = ?", data)
	//}

	// active_begin_time
	//if data, ok := conditions["active_begin_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".active_begin_time = ?", data)
	//}

	// active_end_time
	//if data, ok := conditions["active_end_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".active_end_time = ?", data)
	//}

	// disable_time
	//if data, ok := conditions["disable_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".disable_time = ?", data)
	//}

	// blacklist_time
	//if data, ok := conditions["blacklist_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".blacklist_time = ?", data)
	//}

	// password_hash
	//if data, ok := conditions["password_hash"]; ok {
	//	dbConn = dbConn.Where(tableName+".password_hash = ?", data)
	//}

	return dbConn
}

// UpdateColumns update columns
func (s *userRepo) UpdateColumns(conditions map[string]interface{}) map[string]interface{} {

	// update columns
	updateColumns := make(map[string]interface{})

	// On-demand loading

	// id
	//if data, ok := conditions["id"]; ok {
	//	updateColumns["id"] = data
	//}

	// user_uuid
	//if data, ok := conditions["user_uuid"]; ok {
	//	updateColumns["user_uuid"] = data
	//}

	// created_time
	//if data, ok := conditions["created_time"]; ok {
	//	updateColumns["created_time"] = data
	//}

	// updated_time
	//if data, ok := conditions["updated_time"]; ok {
	//	updateColumns["updated_time"] = data
	//}

	// deleted_time
	//if data, ok := conditions["deleted_time"]; ok {
	//	updateColumns["deleted_time"] = data
	//}

	// is_deleted
	//if data, ok := conditions["is_deleted"]; ok {
	//	updateColumns["is_deleted"] = data
	//}

	// user_email
	//if data, ok := conditions["user_email"]; ok {
	//	updateColumns["user_email"] = data
	//}

	// user_nickname
	//if data, ok := conditions["user_nickname"]; ok {
	//	updateColumns["user_nickname"] = data
	//}

	// user_avatar
	//if data, ok := conditions["user_avatar"]; ok {
	//	updateColumns["user_avatar"] = data
	//}

	// user_gender
	//if data, ok := conditions["user_gender"]; ok {
	//	updateColumns["user_gender"] = data
	//}

	// user_status
	//if data, ok := conditions["user_status"]; ok {
	//	updateColumns["user_status"] = data
	//}

	// active_begin_time
	//if data, ok := conditions["active_begin_time"]; ok {
	//	updateColumns["active_begin_time"] = data
	//}

	// active_end_time
	//if data, ok := conditions["active_end_time"]; ok {
	//	updateColumns["active_end_time"] = data
	//}

	// disable_time
	//if data, ok := conditions["disable_time"]; ok {
	//	updateColumns["disable_time"] = data
	//}

	// blacklist_time
	//if data, ok := conditions["blacklist_time"]; ok {
	//	updateColumns["blacklist_time"] = data
	//}

	// password_hash
	//if data, ok := conditions["password_hash"]; ok {
	//	updateColumns["password_hash"] = data
	//}

	return updateColumns
}
