// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/org/v1/common/org.common.v1.proto

package orgcommonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrgCommon OrgCommon enum
type OrgCommonEnum_OrgCommon int32

const (
	// UNSPECIFIED 未指定
	OrgCommonEnum_UNSPECIFIED OrgCommonEnum_OrgCommon = 0
)

// Enum value maps for OrgCommonEnum_OrgCommon.
var (
	OrgCommonEnum_OrgCommon_name = map[int32]string{
		0: "UNSPECIFIED",
	}
	OrgCommonEnum_OrgCommon_value = map[string]int32{
		"UNSPECIFIED": 0,
	}
)

func (x OrgCommonEnum_OrgCommon) Enum() *OrgCommonEnum_OrgCommon {
	p := new(OrgCommonEnum_OrgCommon)
	*p = x
	return p
}

func (x OrgCommonEnum_OrgCommon) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrgCommonEnum_OrgCommon) Descriptor() protoreflect.EnumDescriptor {
	return file_api_org_v1_common_org_common_v1_proto_enumTypes[0].Descriptor()
}

func (OrgCommonEnum_OrgCommon) Type() protoreflect.EnumType {
	return &file_api_org_v1_common_org_common_v1_proto_enumTypes[0]
}

func (x OrgCommonEnum_OrgCommon) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrgCommonEnum_OrgCommon.Descriptor instead.
func (OrgCommonEnum_OrgCommon) EnumDescriptor() ([]byte, []int) {
	return file_api_org_v1_common_org_common_v1_proto_rawDescGZIP(), []int{0, 0}
}

// OrgCommonEnum OrgCommonEnum enum
type OrgCommonEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrgCommonEnum) Reset() {
	*x = OrgCommonEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_org_v1_common_org_common_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgCommonEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgCommonEnum) ProtoMessage() {}

func (x *OrgCommonEnum) ProtoReflect() protoreflect.Message {
	mi := &file_api_org_v1_common_org_common_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgCommonEnum.ProtoReflect.Descriptor instead.
func (*OrgCommonEnum) Descriptor() ([]byte, []int) {
	return file_api_org_v1_common_org_common_v1_proto_rawDescGZIP(), []int{0}
}

var File_api_org_v1_common_org_common_v1_proto protoreflect.FileDescriptor

var file_api_org_v1_common_org_common_v1_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x72, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x6f, 0x72, 0x67, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x76,
	0x31, 0x22, 0x2d, 0x0a, 0x0d, 0x4f, 0x72, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x45, 0x6e,
	0x75, 0x6d, 0x22, 0x1c, 0x0a, 0x09, 0x4f, 0x72, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12,
	0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x42, 0x71, 0x0a, 0x18, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x6f, 0x72, 0x67, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x76, 0x31, 0x42, 0x13, 0x54, 0x62,
	0x41, 0x70, 0x69, 0x4f, 0x72, 0x67, 0x4f, 0x72, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x56,
	0x31, 0x50, 0x01, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x69, 0x6b, 0x61, 0x69, 0x67, 0x75, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x72, 0x76,
	0x2d, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x72, 0x67, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3b, 0x6f, 0x72, 0x67, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_org_v1_common_org_common_v1_proto_rawDescOnce sync.Once
	file_api_org_v1_common_org_common_v1_proto_rawDescData = file_api_org_v1_common_org_common_v1_proto_rawDesc
)

func file_api_org_v1_common_org_common_v1_proto_rawDescGZIP() []byte {
	file_api_org_v1_common_org_common_v1_proto_rawDescOnce.Do(func() {
		file_api_org_v1_common_org_common_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_org_v1_common_org_common_v1_proto_rawDescData)
	})
	return file_api_org_v1_common_org_common_v1_proto_rawDescData
}

var file_api_org_v1_common_org_common_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_org_v1_common_org_common_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_org_v1_common_org_common_v1_proto_goTypes = []interface{}{
	(OrgCommonEnum_OrgCommon)(0), // 0: user.api.org.orgcommonv1.OrgCommonEnum.OrgCommon
	(*OrgCommonEnum)(nil),        // 1: user.api.org.orgcommonv1.OrgCommonEnum
}
var file_api_org_v1_common_org_common_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_org_v1_common_org_common_v1_proto_init() }
func file_api_org_v1_common_org_common_v1_proto_init() {
	if File_api_org_v1_common_org_common_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_org_v1_common_org_common_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgCommonEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_org_v1_common_org_common_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_org_v1_common_org_common_v1_proto_goTypes,
		DependencyIndexes: file_api_org_v1_common_org_common_v1_proto_depIdxs,
		EnumInfos:         file_api_org_v1_common_org_common_v1_proto_enumTypes,
		MessageInfos:      file_api_org_v1_common_org_common_v1_proto_msgTypes,
	}.Build()
	File_api_org_v1_common_org_common_v1_proto = out.File
	file_api_org_v1_common_org_common_v1_proto_rawDesc = nil
	file_api_org_v1_common_org_common_v1_proto_goTypes = nil
	file_api_org_v1_common_org_common_v1_proto_depIdxs = nil
}
