# app 程序
app:
  name: go-srv-user
  version: 0.0.1
  # env 开发环境；值：DEVELOP、TESTING、PREVIEW、PRODUCTION
  env: develop
  endpoints:
    - https://uufff.com
  metadata:
    id: "${app.name}_${app.version}_${app.env}"
