// Package schemas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package schemas

import (
	migrationuitl "github.com/ikaiguang/go-srv-kit/data/migration"
	gorm "gorm.io/gorm"
	"time"
)

var _ = time.Time{}

// UserRegEmailSchema UserRegEmail
var UserRegEmailSchema UserRegEmail

// NewUserRegEmail new schema
func NewUserRegEmail() *UserRegEmail {
	return &UserRegEmail{}
}

// UserRegEmail ENGINE InnoDB CHARSET utf8mb4 COMMENT '用户-注册-邮箱'
type UserRegEmail struct {
	Id          uint64    `gorm:"column:id;primaryKey;type:uint;autoIncrement;comment:ID" json:"id"`
	UserEmail   string    `gorm:"column:user_email;unique;type:string;size:255;not null;default:'';comment:用户手机号码" json:"user_email"`
	CreatedTime time.Time `gorm:"column:created_time;type:time;not null;comment:创建时间" json:"created_time"`
	UpdatedTime time.Time `gorm:"column:updated_time;type:time;not null;comment:最后修改时间" json:"updated_time"`
	UserUuid    string    `gorm:"column:user_uuid;unique;type:string;size:255;not null;default:'';comment:uuid" json:"user_uuid"`
}

// TableName table name
func (s *UserRegEmail) TableName() string {
	return "srv_user_reg_email"
}

// CreateTableMigrator create table migrator
func (s *UserRegEmail) CreateTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationRepo {
	return migrationuitl.NewCreateTable(migrator, s)
}

// DropTableMigrator create table migrator
func (s *UserRegEmail) DropTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationRepo {
	return migrationuitl.NewDropTable(migrator, s)
}
