// Package schemas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package schemas

import (
	migrationuitl "github.com/ikaiguang/go-srv-kit/data/migration"
	gorm "gorm.io/gorm"
	"time"
)

var _ = time.Time{}

// UserRegUsernameSchema UserRegUsername
var UserRegUsernameSchema UserRegUsername

// NewUserRegUsername new schema
func NewUserRegUsername() *UserRegUsername {
	return &UserRegUsername{}
}

// UserRegUsername ENGINE InnoDB CHARSET utf8mb4 COMMENT '用户-注册-用户名'
type UserRegUsername struct {
	Id          uint64    `gorm:"column:id;primaryKey;type:uint;autoIncrement;comment:ID" json:"id"`
	UserName    string    `gorm:"column:user_name;unique;type:string;size:255;not null;default:'';comment:用户名" json:"user_name"`
	CreatedTime time.Time `gorm:"column:created_time;type:time;not null;comment:创建时间" json:"created_time"`
	UpdatedTime time.Time `gorm:"column:updated_time;type:time;not null;comment:最后修改时间" json:"updated_time"`
	UserUuid    string    `gorm:"column:user_uuid;unique;type:string;size:255;not null;default:'';comment:uuid" json:"user_uuid"`
}

// TableName table name
func (s *UserRegUsername) TableName() string {
	return "srv_user_reg_username"
}

// CreateTableMigrator create table migrator
func (s *UserRegUsername) CreateTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationRepo {
	return migrationuitl.NewCreateTable(migrator, s)
}

// DropTableMigrator create table migrator
func (s *UserRegUsername) DropTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationRepo {
	return migrationuitl.NewDropTable(migrator, s)
}
