// Package schemas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package schemas

import (
	migrationuitl "github.com/ikaiguang/go-srv-kit/data/migration"
	gorm "gorm.io/gorm"
	"time"
)

var _ = time.Time{}

// OrgSchema Org
var OrgSchema Org

// NewOrg new schema
func NewOrg() *Org {
	return &Org{}
}

// Org ENGINE InnoDB CHARSET utf8mb4 COMMENT '组织'
type Org struct {
	Id              uint64     `gorm:"column:id;primaryKey;type:uint;autoIncrement;comment:ID" json:"id"`
	OrgUuid         string     `gorm:"column:org_uuid;unique;type:string;size:255;not null;default:'';comment:uuid" json:"org_uuid"`
	CreatedTime     time.Time  `gorm:"column:created_time;type:time;not null;comment:创建时间" json:"created_time"`
	UpdatedTime     time.Time  `gorm:"column:updated_time;type:time;not null;comment:最后修改时间" json:"updated_time"`
	DeletedTime     *time.Time `gorm:"column:deleted_time;type:time;comment:删除时间" json:"deleted_time"`
	IsDeleted       bool       `gorm:"column:is_deleted;index;type:bool;not null;default:0;comment:是否已删除" json:"is_deleted"`
	OrgEmail        string     `gorm:"column:org_email;type:string;size:255;not null;default:'';comment:邮箱" json:"org_email"`
	OrgName         string     `gorm:"column:org_name;type:string;size:255;not null;default:'';comment:名称" json:"org_name"`
	OrgLogo         string     `gorm:"column:org_logo;type:string;size:255;not null;default:'';comment:logo" json:"org_logo"`
	OrgStatus       string     `gorm:"column:org_status;type:string;size:255;not null;default:'';comment:状态" json:"org_status"`
	ActiveBeginTime *time.Time `gorm:"column:active_begin_time;type:time;comment:激活开始时间" json:"active_begin_time"`
	ActiveEndTime   *time.Time `gorm:"column:active_end_time;type:time;comment:激活结束时间" json:"active_end_time"`
	DisableTime     *time.Time `gorm:"column:disable_time;type:time;comment:禁用时间" json:"disable_time"`
	BlacklistTime   *time.Time `gorm:"column:blacklist_time;type:time;comment:黑名单时间" json:"blacklist_time"`
	PasswordHash    string     `gorm:"column:password_hash;type:string;size:255;not null;default:'';comment:密码" json:"password_hash"`
}

// TableName table name
func (s *Org) TableName() string {
	return "srv_org"
}

// CreateTableMigrator create table migrator
func (s *Org) CreateTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationRepo {
	return migrationuitl.NewCreateTable(migrator, s)
}

// DropTableMigrator create table migrator
func (s *Org) DropTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationRepo {
	return migrationuitl.NewDropTable(migrator, s)
}
