// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/user/v1/resources/user_reg_email.resource.v1.proto

package userv1

import (
	v1 "github.com/ikaiguang/go-srv-kit/api/page/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserRegEmail ENGINE InnoDB CHARSET utf8mb4 COMMENT '用户-注册-邮箱'
type UserRegEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id ID
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// user_email 用户手机号码
	UserEmail string `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	// created_time 创建时间
	CreatedTime string `protobuf:"bytes,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// updated_time 最后修改时间
	UpdatedTime string `protobuf:"bytes,4,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	// user_uuid uuid
	UserUuid string `protobuf:"bytes,5,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
}

func (x *UserRegEmail) Reset() {
	*x = UserRegEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRegEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegEmail) ProtoMessage() {}

func (x *UserRegEmail) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegEmail.ProtoReflect.Descriptor instead.
func (*UserRegEmail) Descriptor() ([]byte, []int) {
	return file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegEmail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserRegEmail) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *UserRegEmail) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *UserRegEmail) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *UserRegEmail) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// UserRegEmailSaveReq save
type UserRegEmailSaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id ID
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// user_email 用户手机号码
	UserEmail string `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	// created_time 创建时间
	CreatedTime string `protobuf:"bytes,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// updated_time 最后修改时间
	UpdatedTime string `protobuf:"bytes,4,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	// user_uuid uuid
	UserUuid string `protobuf:"bytes,5,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
}

func (x *UserRegEmailSaveReq) Reset() {
	*x = UserRegEmailSaveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRegEmailSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegEmailSaveReq) ProtoMessage() {}

func (x *UserRegEmailSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegEmailSaveReq.ProtoReflect.Descriptor instead.
func (*UserRegEmailSaveReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescGZIP(), []int{1}
}

func (x *UserRegEmailSaveReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserRegEmailSaveReq) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *UserRegEmailSaveReq) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *UserRegEmailSaveReq) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *UserRegEmailSaveReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// UserRegEmailIdReq id
type UserRegEmailIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// user_reg_email_id id
	UserRegEmailId int64 `protobuf:"varint,1,opt,name=user_reg_email_id,json=userRegEmailId,proto3" json:"user_reg_email_id,omitempty"`
}

func (x *UserRegEmailIdReq) Reset() {
	*x = UserRegEmailIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRegEmailIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegEmailIdReq) ProtoMessage() {}

func (x *UserRegEmailIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegEmailIdReq.ProtoReflect.Descriptor instead.
func (*UserRegEmailIdReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescGZIP(), []int{2}
}

func (x *UserRegEmailIdReq) GetUserRegEmailId() int64 {
	if x != nil {
		return x.UserRegEmailId
	}
	return 0
}

// UserRegEmailIdsReq ids
type UserRegEmailIdsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// user_reg_email_ids ids
	UserRegEmailIds []int64 `protobuf:"varint,1,rep,packed,name=user_reg_email_ids,json=userRegEmailIds,proto3" json:"user_reg_email_ids,omitempty"`
}

func (x *UserRegEmailIdsReq) Reset() {
	*x = UserRegEmailIdsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRegEmailIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegEmailIdsReq) ProtoMessage() {}

func (x *UserRegEmailIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegEmailIdsReq.ProtoReflect.Descriptor instead.
func (*UserRegEmailIdsReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescGZIP(), []int{3}
}

func (x *UserRegEmailIdsReq) GetUserRegEmailIds() []int64 {
	if x != nil {
		return x.UserRegEmailIds
	}
	return nil
}

// UserRegEmailListReq list
type UserRegEmailListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// page_request paging request
	PageRequest *v1.PageRequest `protobuf:"bytes,1,opt,name=page_request,json=pageRequest,proto3" json:"page_request,omitempty"`
}

func (x *UserRegEmailListReq) Reset() {
	*x = UserRegEmailListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRegEmailListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegEmailListReq) ProtoMessage() {}

func (x *UserRegEmailListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegEmailListReq.ProtoReflect.Descriptor instead.
func (*UserRegEmailListReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescGZIP(), []int{4}
}

func (x *UserRegEmailListReq) GetPageRequest() *v1.PageRequest {
	if x != nil {
		return x.PageRequest
	}
	return nil
}

// UserRegEmailListResp list
type UserRegEmailListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// list UserRegEmail-array
	List []*UserRegEmail `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// page_info paging response
	PageInfo *v1.PageResponse `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
}

func (x *UserRegEmailListResp) Reset() {
	*x = UserRegEmailListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRegEmailListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegEmailListResp) ProtoMessage() {}

func (x *UserRegEmailListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegEmailListResp.ProtoReflect.Descriptor instead.
func (*UserRegEmailListResp) Descriptor() ([]byte, []int) {
	return file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescGZIP(), []int{5}
}

func (x *UserRegEmailListResp) GetList() []*UserRegEmail {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *UserRegEmailListResp) GetPageInfo() *v1.PageResponse {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

// UserRegEmailProcessResult process result
type UserRegEmailProcessResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// success true or false
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UserRegEmailProcessResult) Reset() {
	*x = UserRegEmailProcessResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRegEmailProcessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegEmailProcessResult) ProtoMessage() {}

func (x *UserRegEmailProcessResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegEmailProcessResult.ProtoReflect.Descriptor instead.
func (*UserRegEmailProcessResult) Descriptor() ([]byte, []int) {
	return file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescGZIP(), []int{6}
}

func (x *UserRegEmailProcessResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_user_v1_resources_user_reg_email_resource_v1_proto protoreflect.FileDescriptor

var file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDesc = []byte{
	0x0a, 0x36, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x67,
	0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x76, 0x31, 0x1a, 0x39,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6b, 0x61, 0x69, 0x67,
	0x75, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x72, 0x76, 0x2d, 0x6b, 0x69, 0x74, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x0c, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0xa7, 0x01, 0x0a,
	0x13, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x61, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x11, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x67, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x12,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x67, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x5a, 0x0a, 0x13, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x43, 0x0a, 0x0c, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6b, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6b, 0x69, 0x74, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x76, 0x31, 0x2e,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x35, 0x0a, 0x19, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x68, 0x0a,
	0x14, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x76, 0x31, 0x42, 0x0f, 0x54, 0x62, 0x41, 0x70, 0x69, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x73, 0x65, 0x72, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6b, 0x61, 0x69, 0x67, 0x75, 0x61, 0x6e, 0x67, 0x2f, 0x67,
	0x6f, 0x2d, 0x73, 0x72, 0x76, 0x2d, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x3b, 0x75, 0x73, 0x65, 0x72, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescOnce sync.Once
	file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescData = file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDesc
)

func file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescGZIP() []byte {
	file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescOnce.Do(func() {
		file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescData)
	})
	return file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDescData
}

var file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_user_v1_resources_user_reg_email_resource_v1_proto_goTypes = []interface{}{
	(*UserRegEmail)(nil),              // 0: user.api.user.userv1.UserRegEmail
	(*UserRegEmailSaveReq)(nil),       // 1: user.api.user.userv1.UserRegEmailSaveReq
	(*UserRegEmailIdReq)(nil),         // 2: user.api.user.userv1.UserRegEmailIdReq
	(*UserRegEmailIdsReq)(nil),        // 3: user.api.user.userv1.UserRegEmailIdsReq
	(*UserRegEmailListReq)(nil),       // 4: user.api.user.userv1.UserRegEmailListReq
	(*UserRegEmailListResp)(nil),      // 5: user.api.user.userv1.UserRegEmailListResp
	(*UserRegEmailProcessResult)(nil), // 6: user.api.user.userv1.UserRegEmailProcessResult
	(*v1.PageRequest)(nil),            // 7: kit.api.page.pagev1.PageRequest
	(*v1.PageResponse)(nil),           // 8: kit.api.page.pagev1.PageResponse
}
var file_api_user_v1_resources_user_reg_email_resource_v1_proto_depIdxs = []int32{
	7, // 0: user.api.user.userv1.UserRegEmailListReq.page_request:type_name -> kit.api.page.pagev1.PageRequest
	0, // 1: user.api.user.userv1.UserRegEmailListResp.list:type_name -> user.api.user.userv1.UserRegEmail
	8, // 2: user.api.user.userv1.UserRegEmailListResp.page_info:type_name -> kit.api.page.pagev1.PageResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_user_v1_resources_user_reg_email_resource_v1_proto_init() }
func file_api_user_v1_resources_user_reg_email_resource_v1_proto_init() {
	if File_api_user_v1_resources_user_reg_email_resource_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRegEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRegEmailSaveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRegEmailIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRegEmailIdsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRegEmailListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRegEmailListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRegEmailProcessResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_user_v1_resources_user_reg_email_resource_v1_proto_goTypes,
		DependencyIndexes: file_api_user_v1_resources_user_reg_email_resource_v1_proto_depIdxs,
		MessageInfos:      file_api_user_v1_resources_user_reg_email_resource_v1_proto_msgTypes,
	}.Build()
	File_api_user_v1_resources_user_reg_email_resource_v1_proto = out.File
	file_api_user_v1_resources_user_reg_email_resource_v1_proto_rawDesc = nil
	file_api_user_v1_resources_user_reg_email_resource_v1_proto_goTypes = nil
	file_api_user_v1_resources_user_reg_email_resource_v1_proto_depIdxs = nil
}
