// Package datas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package datas

import (
	"bytes"
	context "context"
	gormutil "github.com/ikaiguang/go-srv-kit/data/gorm"
	gorm "gorm.io/gorm"
	"strings"

	entities "github.com/ikaiguang/go-srv-user/internal/domain/entity/org"
	repos "github.com/ikaiguang/go-srv-user/internal/domain/repo/org"
	schemas "github.com/ikaiguang/go-srv-user/internal/infra/mysql/schema/org"
)

// orgRepo repo
type orgRepo struct {
	dbConn    *gorm.DB    // *gorm.DB
	OrgSchema schemas.Org // Org
}

// NewOrgRepo new data repo
func NewOrgRepo(dbConn *gorm.DB) repos.OrgRepo {
	return &orgRepo{
		dbConn: dbConn,
	}
}

// =============== 创建 ===============

// create insert one
func (s *orgRepo) create(ctx context.Context, dbConn *gorm.DB, dataModel *entities.Org) (err error) {
	err = dbConn.WithContext(ctx).Create(dataModel).Error
	if err != nil {
		return err
	}
	return
}

// Create insert one
func (s *orgRepo) Create(ctx context.Context, dataModel *entities.Org) error {
	return s.create(ctx, s.dbConn, dataModel)
}

// CreateWithDBConn create
func (s *orgRepo) CreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.Org) error {
	return s.create(ctx, dbConn, dataModel)
}

// existCreate exist create
func (s *orgRepo) existCreate(ctx context.Context, dbConn *gorm.DB, dataModel *entities.Org) (anotherModel *entities.Org, isNotFound bool, err error) {
	anotherModel = new(entities.Org)
	err = dbConn.WithContext(ctx).
		Table(s.OrgSchema.TableName()).
		Where("id = ?", dataModel.Id).
		First(anotherModel).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			isNotFound = true
			err = nil
		}
		return
	}
	return
}

// ExistCreate exist create
func (s *orgRepo) ExistCreate(ctx context.Context, dataModel *entities.Org) (anotherModel *entities.Org, isNotFound bool, err error) {
	return s.existCreate(ctx, s.dbConn, dataModel)
}

// ExistCreateWithDBConn exist create
func (s *orgRepo) ExistCreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.Org) (anotherModel *entities.Org, isNotFound bool, err error) {
	return s.existCreate(ctx, dbConn, dataModel)
}

// createInBatches create many
func (s *orgRepo) createInBatches(ctx context.Context, dbConn *gorm.DB, dataModels []*entities.Org, batchSize int) (err error) {
	err = dbConn.WithContext(ctx).CreateInBatches(dataModels, batchSize).Error
	if err != nil {
		return err
	}
	return
}

// CreateInBatches create many
func (s *orgRepo) CreateInBatches(ctx context.Context, dataModels []*entities.Org, batchSize int) error {
	return s.createInBatches(ctx, s.dbConn, dataModels, batchSize)
}

// CreateInBatchesWithDBConn create many
func (s *orgRepo) CreateInBatchesWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*entities.Org, batchSize int) error {
	return s.createInBatches(ctx, dbConn, dataModels, batchSize)
}

// =============== 更新 ===============

// update update
func (s *orgRepo) update(ctx context.Context, dbConn *gorm.DB, dataModel *entities.Org) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.OrgSchema.TableName()).
		Where("id = ?", dataModel.Id).
		Save(dataModel).Error
	if err != nil {
		return err
	}
	return
}

// Update update
func (s *orgRepo) Update(ctx context.Context, dataModel *entities.Org) error {
	return s.update(ctx, s.dbConn, dataModel)
}

// UpdateWithDBConn update
func (s *orgRepo) UpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.Org) error {
	return s.update(ctx, dbConn, dataModel)
}

// existUpdate exist update
func (s *orgRepo) existUpdate(ctx context.Context, dbConn *gorm.DB, dataModel *entities.Org) (anotherModel *entities.Org, isNotFound bool, err error) {
	anotherModel = new(entities.Org)
	err = dbConn.WithContext(ctx).
		Table(s.OrgSchema.TableName()).
		Where("id = ?", dataModel.Id).
		Where("id != ?", dataModel.Id).
		First(anotherModel).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			isNotFound = true
			err = nil
		}
		return
	}
	return
}

// ExistUpdate exist update
func (s *orgRepo) ExistUpdate(ctx context.Context, dataModel *entities.Org) (anotherModel *entities.Org, isNotFound bool, err error) {
	return s.existUpdate(ctx, s.dbConn, dataModel)
}

// ExistUpdateWithDBConn exist update
func (s *orgRepo) ExistUpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.Org) (anotherModel *entities.Org, isNotFound bool, err error) {
	return s.existUpdate(ctx, dbConn, dataModel)
}

// =============== query one : 查一个 ===============

// queryOneById query one by id
func (s *orgRepo) queryOneById(ctx context.Context, dbConn *gorm.DB, id interface{}) (dataModel *entities.Org, isNotFound bool, err error) {
	dataModel = new(entities.Org)
	err = dbConn.WithContext(ctx).
		Table(s.OrgSchema.TableName()).
		Where("id = ?", id).
		First(dataModel).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			err = nil
			isNotFound = true
		}
		return
	}
	return
}

// QueryOneById query one by id
func (s *orgRepo) QueryOneById(ctx context.Context, id interface{}) (dataModel *entities.Org, isNotFound bool, err error) {
	return s.queryOneById(ctx, s.dbConn, id)
}

// QueryOneByIdWithDBConn query one by id
func (s *orgRepo) QueryOneByIdWithDBConn(ctx context.Context, dbConn *gorm.DB, id interface{}) (dataModel *entities.Org, isNotFound bool, err error) {
	return s.queryOneById(ctx, dbConn, id)
}

// queryOneByConditions query one by conditions
func (s *orgRepo) queryOneByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *entities.Org, isNotFound bool, err error) {
	dataModel = new(entities.Org)
	dbConn = dbConn.WithContext(ctx).Table(s.OrgSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		First(dataModel).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			err = nil
			isNotFound = true
		}
		return
	}
	return
}

// QueryOneByConditions query one by conditions
func (s *orgRepo) QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *entities.Org, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, s.dbConn, conditions)
}

// QueryOneByConditionsWithDBConn query one by conditions
func (s *orgRepo) QueryOneByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *entities.Org, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, dbConn, conditions)
}

// =============== query all : 查全部 ===============

// queryAllByConditions query all by conditions
func (s *orgRepo) queryAllByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModels []*entities.Org, err error) {
	dbConn = dbConn.WithContext(ctx).Table(s.OrgSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		Find(&dataModels).Error
	if err != nil {
		return dataModels, err
	}
	return
}

// QueryAllByConditions query all by conditions
func (s *orgRepo) QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) ([]*entities.Org, error) {
	return s.queryAllByConditions(ctx, s.dbConn, conditions)
}

// QueryAllByConditionsWithDBConn query all by conditions
func (s *orgRepo) QueryAllByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) ([]*entities.Org, error) {
	return s.queryAllByConditions(ctx, dbConn, conditions)
}

// =============== list : 列表 ===============

// list 列表
func (s *orgRepo) list(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormutil.PaginatorArgs) (dataModels []*entities.Org, recordCount int64, err error) {
	// query where
	dbConn = dbConn.WithContext(ctx).Table(s.OrgSchema.TableName())
	dbConn = s.WhereConditions(dbConn, conditions)
	dbConn = gormutil.AssembleWheres(dbConn, paginatorArgs.PageWheres)

	err = dbConn.Count(&recordCount).Error
	if err != nil {
		return
	} else if recordCount == 0 {
		return // empty
	}

	// pagination
	dbConn = gormutil.AssembleOrders(dbConn, paginatorArgs.PageOrders)
	err = gormutil.Paginator(dbConn, paginatorArgs.PageOption).
		Find(&dataModels).Error
	if err != nil {
		return
	}
	return
}

// List 列表
func (s *orgRepo) List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormutil.PaginatorArgs) ([]*entities.Org, int64, error) {
	return s.list(ctx, s.dbConn, conditions, paginatorArgs)
}

// ListWithDBConn 列表
func (s *orgRepo) ListWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormutil.PaginatorArgs) ([]*entities.Org, int64, error) {
	return s.list(ctx, dbConn, conditions, paginatorArgs)
}

// =============== delete : 删除 ===============

// delete delete one
func (s *orgRepo) delete(ctx context.Context, dbConn *gorm.DB, dataModel *entities.Org) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.OrgSchema.TableName()).
		Where("id = ?", dataModel.Id).
		Delete(dataModel).Error
	if err != nil {
		return err
	}
	return
}

// Delete delete one
func (s *orgRepo) Delete(ctx context.Context, dataModel *entities.Org) error {
	return s.delete(ctx, s.dbConn, dataModel)
}

// DeleteWithDBConn delete one
func (s *orgRepo) DeleteWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.Org) error {
	return s.delete(ctx, dbConn, dataModel)
}

// deleteByIds delete by ids
func (s *orgRepo) deleteByIds(ctx context.Context, dbConn *gorm.DB, ids interface{}) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.OrgSchema.TableName()).
		Where("id in (?)", ids).
		Delete(entities.Org{}).Error
	if err != nil {
		return err
	}
	return
}

// DeleteByIds delete by ids
func (s *orgRepo) DeleteByIds(ctx context.Context, ids interface{}) error {
	return s.deleteByIds(ctx, s.dbConn, ids)
}

// DeleteByIdsWithDBConn delete by ids
func (s *orgRepo) DeleteByIdsWithDBConn(ctx context.Context, dbConn *gorm.DB, ids interface{}) error {
	return s.deleteByIds(ctx, dbConn, ids)
}

// =============== insert : 批量入库 ===============

var _ gormutil.BatchInsertRepo = new(OrgSlice)

// OrgSlice 表切片
type OrgSlice []*entities.Org

// TableName 表名
func (s *OrgSlice) TableName() string {
	if len(*s) > 0 {
		return (*s)[0].TableName()
	}
	return (&entities.Org{}).TableName()
}

// Len 长度
func (s *OrgSlice) Len() int {
	return len(*s)
}

// InsertColumns 批量入库的列
func (s *OrgSlice) InsertColumns() (columnList []string, placeholder string) {
	// columns
	columnList = []string{
		"org_uuid", "created_time", "updated_time", "deleted_time", "is_deleted", "org_email",
		"org_name", "org_logo", "org_status", "active_begin_time", "active_end_time", "disable_time",
		"blacklist_time", "password_hash",
	}

	// placeholders
	insertPlaceholderBytes := bytes.Repeat([]byte("?, "), len(columnList))
	insertPlaceholderBytes = bytes.TrimSuffix(insertPlaceholderBytes, []byte(", "))

	return columnList, string(insertPlaceholderBytes)
}

// InsertValues 批量入库的值
func (s *OrgSlice) InsertValues(args *gormutil.BatchInsertValueArgs) (prepareData []interface{}, placeholderSlice []string) {
	dataModels := (*s)[args.StepStart:args.StepEnd]
	for index := range dataModels {
		// placeholder
		placeholderSlice = append(placeholderSlice, "("+args.InsertPlaceholder+")")

		// prepare data
		prepareData = append(prepareData, dataModels[index].OrgUuid)
		prepareData = append(prepareData, dataModels[index].CreatedTime)
		prepareData = append(prepareData, dataModels[index].UpdatedTime)
		prepareData = append(prepareData, dataModels[index].DeletedTime)
		prepareData = append(prepareData, dataModels[index].IsDeleted)
		prepareData = append(prepareData, dataModels[index].OrgEmail)
		prepareData = append(prepareData, dataModels[index].OrgName)
		prepareData = append(prepareData, dataModels[index].OrgLogo)
		prepareData = append(prepareData, dataModels[index].OrgStatus)
		prepareData = append(prepareData, dataModels[index].ActiveBeginTime)
		prepareData = append(prepareData, dataModels[index].ActiveEndTime)
		prepareData = append(prepareData, dataModels[index].DisableTime)
		prepareData = append(prepareData, dataModels[index].BlacklistTime)
		prepareData = append(prepareData, dataModels[index].PasswordHash)
	}
	return prepareData, placeholderSlice
}

// UpdateColumns 批量入库的列
func (s *OrgSlice) UpdateColumns() (columnList []string) {
	// columns
	columnList = []string{
		"org_uuid=excluded.org_uuid", "created_time=excluded.created_time", "updated_time=excluded.updated_time",
		"deleted_time=excluded.deleted_time", "is_deleted=excluded.is_deleted", "org_email=excluded.org_email",
		"org_name=excluded.org_name", "org_logo=excluded.org_logo", "org_status=excluded.org_status",
		"active_begin_time=excluded.active_begin_time", "active_end_time=excluded.active_end_time", "disable_time=excluded.disable_time",
		"blacklist_time=excluded.blacklist_time", "password_hash=excluded.password_hash",
	}
	return columnList
}

// ConflictActionForMySQL 更新冲突时的操作
func (s *OrgSlice) ConflictActionForMySQL() (req *gormutil.BatchInsertConflictActionReq) {
	req = &gormutil.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "AS excluded",
		OnConflictTarget:      "ON DUPLICATE KEY",
		OnConflictAction:      "UPDATE " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// ConflictActionForPostgres 更新冲突时的操作
func (s *OrgSlice) ConflictActionForPostgres() (req *gormutil.BatchInsertConflictActionReq) {
	req = &gormutil.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "",
		OnConflictTarget:      "ON CONFLICT(id)",
		OnConflictAction:      "DO UPDATE SET " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// insert 批量插入
func (s *orgRepo) insert(ctx context.Context, dbConn *gorm.DB, dataModels OrgSlice) error {
	return gormutil.BatchInsertWithContext(ctx, dbConn, &dataModels)
}

// Insert 批量插入
func (s *orgRepo) Insert(ctx context.Context, dataModels []*entities.Org) error {
	return s.insert(ctx, s.dbConn, dataModels)
}

// InsertWithDBConn 批量插入
func (s *orgRepo) InsertWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*entities.Org) error {
	return s.insert(ctx, dbConn, dataModels)
}

// =============== conditions : 条件 ===============

// WhereConditions orm where
func (s *orgRepo) WhereConditions(dbConn *gorm.DB, conditions map[string]interface{}) *gorm.DB {

	// table name
	//tableName := s.OrgSchema.TableName()

	// On-demand loading

	// id
	//if data, ok := conditions["id"]; ok {
	//	dbConn = dbConn.Where(tableName+".id = ?", data)
	//}

	// org_uuid
	//if data, ok := conditions["org_uuid"]; ok {
	//	dbConn = dbConn.Where(tableName+".org_uuid = ?", data)
	//}

	// created_time
	//if data, ok := conditions["created_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".created_time = ?", data)
	//}

	// updated_time
	//if data, ok := conditions["updated_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".updated_time = ?", data)
	//}

	// deleted_time
	//if data, ok := conditions["deleted_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".deleted_time = ?", data)
	//}

	// is_deleted
	//if data, ok := conditions["is_deleted"]; ok {
	//	dbConn = dbConn.Where(tableName+".is_deleted = ?", data)
	//}

	// org_email
	//if data, ok := conditions["org_email"]; ok {
	//	dbConn = dbConn.Where(tableName+".org_email = ?", data)
	//}

	// org_name
	//if data, ok := conditions["org_name"]; ok {
	//	dbConn = dbConn.Where(tableName+".org_name = ?", data)
	//}

	// org_logo
	//if data, ok := conditions["org_logo"]; ok {
	//	dbConn = dbConn.Where(tableName+".org_logo = ?", data)
	//}

	// org_status
	//if data, ok := conditions["org_status"]; ok {
	//	dbConn = dbConn.Where(tableName+".org_status = ?", data)
	//}

	// active_begin_time
	//if data, ok := conditions["active_begin_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".active_begin_time = ?", data)
	//}

	// active_end_time
	//if data, ok := conditions["active_end_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".active_end_time = ?", data)
	//}

	// disable_time
	//if data, ok := conditions["disable_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".disable_time = ?", data)
	//}

	// blacklist_time
	//if data, ok := conditions["blacklist_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".blacklist_time = ?", data)
	//}

	// password_hash
	//if data, ok := conditions["password_hash"]; ok {
	//	dbConn = dbConn.Where(tableName+".password_hash = ?", data)
	//}

	return dbConn
}

// UpdateColumns update columns
func (s *orgRepo) UpdateColumns(conditions map[string]interface{}) map[string]interface{} {

	// update columns
	updateColumns := make(map[string]interface{})

	// On-demand loading

	// id
	//if data, ok := conditions["id"]; ok {
	//	updateColumns["id"] = data
	//}

	// org_uuid
	//if data, ok := conditions["org_uuid"]; ok {
	//	updateColumns["org_uuid"] = data
	//}

	// created_time
	//if data, ok := conditions["created_time"]; ok {
	//	updateColumns["created_time"] = data
	//}

	// updated_time
	//if data, ok := conditions["updated_time"]; ok {
	//	updateColumns["updated_time"] = data
	//}

	// deleted_time
	//if data, ok := conditions["deleted_time"]; ok {
	//	updateColumns["deleted_time"] = data
	//}

	// is_deleted
	//if data, ok := conditions["is_deleted"]; ok {
	//	updateColumns["is_deleted"] = data
	//}

	// org_email
	//if data, ok := conditions["org_email"]; ok {
	//	updateColumns["org_email"] = data
	//}

	// org_name
	//if data, ok := conditions["org_name"]; ok {
	//	updateColumns["org_name"] = data
	//}

	// org_logo
	//if data, ok := conditions["org_logo"]; ok {
	//	updateColumns["org_logo"] = data
	//}

	// org_status
	//if data, ok := conditions["org_status"]; ok {
	//	updateColumns["org_status"] = data
	//}

	// active_begin_time
	//if data, ok := conditions["active_begin_time"]; ok {
	//	updateColumns["active_begin_time"] = data
	//}

	// active_end_time
	//if data, ok := conditions["active_end_time"]; ok {
	//	updateColumns["active_end_time"] = data
	//}

	// disable_time
	//if data, ok := conditions["disable_time"]; ok {
	//	updateColumns["disable_time"] = data
	//}

	// blacklist_time
	//if data, ok := conditions["blacklist_time"]; ok {
	//	updateColumns["blacklist_time"] = data
	//}

	// password_hash
	//if data, ok := conditions["password_hash"]; ok {
	//	updateColumns["password_hash"] = data
	//}

	return updateColumns
}
