// Package entities
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package entities

import (
	"time"
)

var _ = time.Time{}

// User ENGINE InnoDB CHARSET utf8mb4 COMMENT '用户'
type User struct {
	Id              uint64     `gorm:"column:id;primaryKey" json:"id"`                    // ID
	UserUuid        string     `gorm:"column:user_uuid" json:"user_uuid"`                 // uuid
	CreatedTime     time.Time  `gorm:"column:created_time" json:"created_time"`           // 创建时间
	UpdatedTime     time.Time  `gorm:"column:updated_time" json:"updated_time"`           // 最后修改时间
	DeletedTime     *time.Time `gorm:"column:deleted_time" json:"deleted_time"`           // 删除时间
	IsDeleted       bool       `gorm:"column:is_deleted" json:"is_deleted"`               // 是否已删除
	UserEmail       string     `gorm:"column:user_email" json:"user_email"`               // 邮箱
	UserNickname    string     `gorm:"column:user_nickname" json:"user_nickname"`         // 昵称
	UserAvatar      string     `gorm:"column:user_avatar" json:"user_avatar"`             // 头像
	UserGender      string     `gorm:"column:user_gender" json:"user_gender"`             // 性别
	UserStatus      string     `gorm:"column:user_status" json:"user_status"`             // 状态
	ActiveBeginTime *time.Time `gorm:"column:active_begin_time" json:"active_begin_time"` // 激活开始时间
	ActiveEndTime   *time.Time `gorm:"column:active_end_time" json:"active_end_time"`     // 激活结束时间
	DisableTime     *time.Time `gorm:"column:disable_time" json:"disable_time"`           // 禁用时间
	BlacklistTime   *time.Time `gorm:"column:blacklist_time" json:"blacklist_time"`       // 黑名单时间
	PasswordHash    string     `gorm:"column:password_hash" json:"password_hash"`         // 密码
}

// TableName table name
func (s *User) TableName() string {
	return "srv_user"
}
