// Package entities
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package entities

import (
	"time"
)

var _ = time.Time{}

// UserRegUsername ENGINE InnoDB CHARSET utf8mb4 COMMENT '用户-注册-用户名'
type UserRegUsername struct {
	Id          uint64    `gorm:"column:id;primaryKey" json:"id"`          // ID
	UserName    string    `gorm:"column:user_name" json:"user_name"`       // 用户名
	CreatedTime time.Time `gorm:"column:created_time" json:"created_time"` // 创建时间
	UpdatedTime time.Time `gorm:"column:updated_time" json:"updated_time"` // 最后修改时间
	UserUuid    string    `gorm:"column:user_uuid" json:"user_uuid"`       // uuid
}

// TableName table name
func (s *UserRegUsername) TableName() string {
	return "srv_user_reg_username"
}
