// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api/user/v1/services/user_reg_username.service.v1.proto

package userservicev1

import (
	context "context"
	resources "github.com/ikaiguang/go-srv-user/api/user/v1/resources"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SrvUserRegUsernameClient is the client API for SrvUserRegUsername service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrvUserRegUsernameClient interface {
	// GetById get by id
	GetById(ctx context.Context, in *resources.UserRegUsernameIdReq, opts ...grpc.CallOption) (*resources.UserRegUsername, error)
	// List list
	List(ctx context.Context, in *resources.UserRegUsernameListReq, opts ...grpc.CallOption) (*resources.UserRegUsernameListResp, error)
	// Create create
	Create(ctx context.Context, in *resources.UserRegUsernameSaveReq, opts ...grpc.CallOption) (*resources.UserRegUsername, error)
	// Update update
	Update(ctx context.Context, in *resources.UserRegUsernameSaveReq, opts ...grpc.CallOption) (*resources.UserRegUsername, error)
	// Delete delete
	Delete(ctx context.Context, in *resources.UserRegUsernameIdReq, opts ...grpc.CallOption) (*resources.UserRegUsernameProcessResult, error)
	// Destroy destroy
	Destroy(ctx context.Context, in *resources.UserRegUsernameIdsReq, opts ...grpc.CallOption) (*resources.UserRegUsernameProcessResult, error)
}

type srvUserRegUsernameClient struct {
	cc grpc.ClientConnInterface
}

func NewSrvUserRegUsernameClient(cc grpc.ClientConnInterface) SrvUserRegUsernameClient {
	return &srvUserRegUsernameClient{cc}
}

func (c *srvUserRegUsernameClient) GetById(ctx context.Context, in *resources.UserRegUsernameIdReq, opts ...grpc.CallOption) (*resources.UserRegUsername, error) {
	out := new(resources.UserRegUsername)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUserRegUsername/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserRegUsernameClient) List(ctx context.Context, in *resources.UserRegUsernameListReq, opts ...grpc.CallOption) (*resources.UserRegUsernameListResp, error) {
	out := new(resources.UserRegUsernameListResp)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUserRegUsername/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserRegUsernameClient) Create(ctx context.Context, in *resources.UserRegUsernameSaveReq, opts ...grpc.CallOption) (*resources.UserRegUsername, error) {
	out := new(resources.UserRegUsername)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUserRegUsername/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserRegUsernameClient) Update(ctx context.Context, in *resources.UserRegUsernameSaveReq, opts ...grpc.CallOption) (*resources.UserRegUsername, error) {
	out := new(resources.UserRegUsername)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUserRegUsername/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserRegUsernameClient) Delete(ctx context.Context, in *resources.UserRegUsernameIdReq, opts ...grpc.CallOption) (*resources.UserRegUsernameProcessResult, error) {
	out := new(resources.UserRegUsernameProcessResult)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUserRegUsername/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserRegUsernameClient) Destroy(ctx context.Context, in *resources.UserRegUsernameIdsReq, opts ...grpc.CallOption) (*resources.UserRegUsernameProcessResult, error) {
	out := new(resources.UserRegUsernameProcessResult)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUserRegUsername/Destroy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvUserRegUsernameServer is the server API for SrvUserRegUsername service.
// All implementations must embed UnimplementedSrvUserRegUsernameServer
// for forward compatibility
type SrvUserRegUsernameServer interface {
	// GetById get by id
	GetById(context.Context, *resources.UserRegUsernameIdReq) (*resources.UserRegUsername, error)
	// List list
	List(context.Context, *resources.UserRegUsernameListReq) (*resources.UserRegUsernameListResp, error)
	// Create create
	Create(context.Context, *resources.UserRegUsernameSaveReq) (*resources.UserRegUsername, error)
	// Update update
	Update(context.Context, *resources.UserRegUsernameSaveReq) (*resources.UserRegUsername, error)
	// Delete delete
	Delete(context.Context, *resources.UserRegUsernameIdReq) (*resources.UserRegUsernameProcessResult, error)
	// Destroy destroy
	Destroy(context.Context, *resources.UserRegUsernameIdsReq) (*resources.UserRegUsernameProcessResult, error)
	mustEmbedUnimplementedSrvUserRegUsernameServer()
}

// UnimplementedSrvUserRegUsernameServer must be embedded to have forward compatible implementations.
type UnimplementedSrvUserRegUsernameServer struct {
}

func (UnimplementedSrvUserRegUsernameServer) GetById(context.Context, *resources.UserRegUsernameIdReq) (*resources.UserRegUsername, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedSrvUserRegUsernameServer) List(context.Context, *resources.UserRegUsernameListReq) (*resources.UserRegUsernameListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSrvUserRegUsernameServer) Create(context.Context, *resources.UserRegUsernameSaveReq) (*resources.UserRegUsername, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSrvUserRegUsernameServer) Update(context.Context, *resources.UserRegUsernameSaveReq) (*resources.UserRegUsername, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSrvUserRegUsernameServer) Delete(context.Context, *resources.UserRegUsernameIdReq) (*resources.UserRegUsernameProcessResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSrvUserRegUsernameServer) Destroy(context.Context, *resources.UserRegUsernameIdsReq) (*resources.UserRegUsernameProcessResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedSrvUserRegUsernameServer) mustEmbedUnimplementedSrvUserRegUsernameServer() {}

// UnsafeSrvUserRegUsernameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvUserRegUsernameServer will
// result in compilation errors.
type UnsafeSrvUserRegUsernameServer interface {
	mustEmbedUnimplementedSrvUserRegUsernameServer()
}

func RegisterSrvUserRegUsernameServer(s grpc.ServiceRegistrar, srv SrvUserRegUsernameServer) {
	s.RegisterService(&SrvUserRegUsername_ServiceDesc, srv)
}

func _SrvUserRegUsername_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.UserRegUsernameIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserRegUsernameServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUserRegUsername/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserRegUsernameServer).GetById(ctx, req.(*resources.UserRegUsernameIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUserRegUsername_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.UserRegUsernameListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserRegUsernameServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUserRegUsername/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserRegUsernameServer).List(ctx, req.(*resources.UserRegUsernameListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUserRegUsername_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.UserRegUsernameSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserRegUsernameServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUserRegUsername/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserRegUsernameServer).Create(ctx, req.(*resources.UserRegUsernameSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUserRegUsername_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.UserRegUsernameSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserRegUsernameServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUserRegUsername/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserRegUsernameServer).Update(ctx, req.(*resources.UserRegUsernameSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUserRegUsername_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.UserRegUsernameIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserRegUsernameServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUserRegUsername/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserRegUsernameServer).Delete(ctx, req.(*resources.UserRegUsernameIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUserRegUsername_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.UserRegUsernameIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserRegUsernameServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUserRegUsername/Destroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserRegUsernameServer).Destroy(ctx, req.(*resources.UserRegUsernameIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SrvUserRegUsername_ServiceDesc is the grpc.ServiceDesc for SrvUserRegUsername service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvUserRegUsername_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.api.user.userservicev1.SrvUserRegUsername",
	HandlerType: (*SrvUserRegUsernameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _SrvUserRegUsername_GetById_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SrvUserRegUsername_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SrvUserRegUsername_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SrvUserRegUsername_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SrvUserRegUsername_Delete_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _SrvUserRegUsername_Destroy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/v1/services/user_reg_username.service.v1.proto",
}
