// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api/user/v1/services/user_reg_mobile.service.v1.proto

package userservicev1

import (
	context "context"
	resources "github.com/ikaiguang/go-srv-user/api/user/v1/resources"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SrvUserRegMobileClient is the client API for SrvUserRegMobile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrvUserRegMobileClient interface {
	// GetById get by id
	GetById(ctx context.Context, in *resources.UserRegMobileIdReq, opts ...grpc.CallOption) (*resources.UserRegMobile, error)
	// List list
	List(ctx context.Context, in *resources.UserRegMobileListReq, opts ...grpc.CallOption) (*resources.UserRegMobileListResp, error)
	// Create create
	Create(ctx context.Context, in *resources.UserRegMobileSaveReq, opts ...grpc.CallOption) (*resources.UserRegMobile, error)
	// Update update
	Update(ctx context.Context, in *resources.UserRegMobileSaveReq, opts ...grpc.CallOption) (*resources.UserRegMobile, error)
	// Delete delete
	Delete(ctx context.Context, in *resources.UserRegMobileIdReq, opts ...grpc.CallOption) (*resources.UserRegMobileProcessResult, error)
	// Destroy destroy
	Destroy(ctx context.Context, in *resources.UserRegMobileIdsReq, opts ...grpc.CallOption) (*resources.UserRegMobileProcessResult, error)
}

type srvUserRegMobileClient struct {
	cc grpc.ClientConnInterface
}

func NewSrvUserRegMobileClient(cc grpc.ClientConnInterface) SrvUserRegMobileClient {
	return &srvUserRegMobileClient{cc}
}

func (c *srvUserRegMobileClient) GetById(ctx context.Context, in *resources.UserRegMobileIdReq, opts ...grpc.CallOption) (*resources.UserRegMobile, error) {
	out := new(resources.UserRegMobile)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUserRegMobile/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserRegMobileClient) List(ctx context.Context, in *resources.UserRegMobileListReq, opts ...grpc.CallOption) (*resources.UserRegMobileListResp, error) {
	out := new(resources.UserRegMobileListResp)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUserRegMobile/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserRegMobileClient) Create(ctx context.Context, in *resources.UserRegMobileSaveReq, opts ...grpc.CallOption) (*resources.UserRegMobile, error) {
	out := new(resources.UserRegMobile)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUserRegMobile/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserRegMobileClient) Update(ctx context.Context, in *resources.UserRegMobileSaveReq, opts ...grpc.CallOption) (*resources.UserRegMobile, error) {
	out := new(resources.UserRegMobile)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUserRegMobile/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserRegMobileClient) Delete(ctx context.Context, in *resources.UserRegMobileIdReq, opts ...grpc.CallOption) (*resources.UserRegMobileProcessResult, error) {
	out := new(resources.UserRegMobileProcessResult)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUserRegMobile/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserRegMobileClient) Destroy(ctx context.Context, in *resources.UserRegMobileIdsReq, opts ...grpc.CallOption) (*resources.UserRegMobileProcessResult, error) {
	out := new(resources.UserRegMobileProcessResult)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUserRegMobile/Destroy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvUserRegMobileServer is the server API for SrvUserRegMobile service.
// All implementations must embed UnimplementedSrvUserRegMobileServer
// for forward compatibility
type SrvUserRegMobileServer interface {
	// GetById get by id
	GetById(context.Context, *resources.UserRegMobileIdReq) (*resources.UserRegMobile, error)
	// List list
	List(context.Context, *resources.UserRegMobileListReq) (*resources.UserRegMobileListResp, error)
	// Create create
	Create(context.Context, *resources.UserRegMobileSaveReq) (*resources.UserRegMobile, error)
	// Update update
	Update(context.Context, *resources.UserRegMobileSaveReq) (*resources.UserRegMobile, error)
	// Delete delete
	Delete(context.Context, *resources.UserRegMobileIdReq) (*resources.UserRegMobileProcessResult, error)
	// Destroy destroy
	Destroy(context.Context, *resources.UserRegMobileIdsReq) (*resources.UserRegMobileProcessResult, error)
	mustEmbedUnimplementedSrvUserRegMobileServer()
}

// UnimplementedSrvUserRegMobileServer must be embedded to have forward compatible implementations.
type UnimplementedSrvUserRegMobileServer struct {
}

func (UnimplementedSrvUserRegMobileServer) GetById(context.Context, *resources.UserRegMobileIdReq) (*resources.UserRegMobile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedSrvUserRegMobileServer) List(context.Context, *resources.UserRegMobileListReq) (*resources.UserRegMobileListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSrvUserRegMobileServer) Create(context.Context, *resources.UserRegMobileSaveReq) (*resources.UserRegMobile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSrvUserRegMobileServer) Update(context.Context, *resources.UserRegMobileSaveReq) (*resources.UserRegMobile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSrvUserRegMobileServer) Delete(context.Context, *resources.UserRegMobileIdReq) (*resources.UserRegMobileProcessResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSrvUserRegMobileServer) Destroy(context.Context, *resources.UserRegMobileIdsReq) (*resources.UserRegMobileProcessResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedSrvUserRegMobileServer) mustEmbedUnimplementedSrvUserRegMobileServer() {}

// UnsafeSrvUserRegMobileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvUserRegMobileServer will
// result in compilation errors.
type UnsafeSrvUserRegMobileServer interface {
	mustEmbedUnimplementedSrvUserRegMobileServer()
}

func RegisterSrvUserRegMobileServer(s grpc.ServiceRegistrar, srv SrvUserRegMobileServer) {
	s.RegisterService(&SrvUserRegMobile_ServiceDesc, srv)
}

func _SrvUserRegMobile_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.UserRegMobileIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserRegMobileServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUserRegMobile/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserRegMobileServer).GetById(ctx, req.(*resources.UserRegMobileIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUserRegMobile_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.UserRegMobileListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserRegMobileServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUserRegMobile/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserRegMobileServer).List(ctx, req.(*resources.UserRegMobileListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUserRegMobile_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.UserRegMobileSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserRegMobileServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUserRegMobile/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserRegMobileServer).Create(ctx, req.(*resources.UserRegMobileSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUserRegMobile_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.UserRegMobileSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserRegMobileServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUserRegMobile/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserRegMobileServer).Update(ctx, req.(*resources.UserRegMobileSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUserRegMobile_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.UserRegMobileIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserRegMobileServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUserRegMobile/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserRegMobileServer).Delete(ctx, req.(*resources.UserRegMobileIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUserRegMobile_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.UserRegMobileIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserRegMobileServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUserRegMobile/Destroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserRegMobileServer).Destroy(ctx, req.(*resources.UserRegMobileIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SrvUserRegMobile_ServiceDesc is the grpc.ServiceDesc for SrvUserRegMobile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvUserRegMobile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.api.user.userservicev1.SrvUserRegMobile",
	HandlerType: (*SrvUserRegMobileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _SrvUserRegMobile_GetById_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SrvUserRegMobile_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SrvUserRegMobile_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SrvUserRegMobile_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SrvUserRegMobile_Delete_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _SrvUserRegMobile_Destroy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/v1/services/user_reg_mobile.service.v1.proto",
}
