// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api/user/v1/services/user.service.v1.proto

package userservicev1

import (
	context "context"
	resources "github.com/ikaiguang/go-srv-user/api/user/v1/resources"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SrvUserClient is the client API for SrvUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrvUserClient interface {
	// Login 用户登录
	Login(ctx context.Context, in *resources.LoginRequest, opts ...grpc.CallOption) (*resources.LoginResponse, error)
	// Register 用户注册
	Register(ctx context.Context, in *resources.RegisterRequest, opts ...grpc.CallOption) (*resources.RegisterResponse, error)
	// Info 用户信息
	Info(ctx context.Context, in *resources.InfoRequest, opts ...grpc.CallOption) (*resources.Info, error)
	// ChangePassword 用户修改密码
	ChangePassword(ctx context.Context, in *resources.ChangePasswordRequest, opts ...grpc.CallOption) (*resources.ChangePasswordResponse, error)
	// ChangeAvatar 用户修改头像
	ChangeAvatar(ctx context.Context, in *resources.ChangeAvatarRequest, opts ...grpc.CallOption) (*resources.ChangeAvatarResponse, error)
	// ChangeMobile 用户修改手机号
	ChangeMobile(ctx context.Context, in *resources.ChangeMobileRequest, opts ...grpc.CallOption) (*resources.ChangeMobileResponse, error)
	// ChangeEmail 用户修改邮箱
	ChangeEmail(ctx context.Context, in *resources.ChangeEmailRequest, opts ...grpc.CallOption) (*resources.ChangeEmailResponse, error)
	// ChangeNickname 用户修改昵称
	ChangeNickname(ctx context.Context, in *resources.ChangeNicknameRequest, opts ...grpc.CallOption) (*resources.ChangeNicknameResponse, error)
	// ChangeSex 用户修改性别
	ChangeSex(ctx context.Context, in *resources.ChangeSexRequest, opts ...grpc.CallOption) (*resources.ChangeSexResponse, error)
}

type srvUserClient struct {
	cc grpc.ClientConnInterface
}

func NewSrvUserClient(cc grpc.ClientConnInterface) SrvUserClient {
	return &srvUserClient{cc}
}

func (c *srvUserClient) Login(ctx context.Context, in *resources.LoginRequest, opts ...grpc.CallOption) (*resources.LoginResponse, error) {
	out := new(resources.LoginResponse)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUser/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserClient) Register(ctx context.Context, in *resources.RegisterRequest, opts ...grpc.CallOption) (*resources.RegisterResponse, error) {
	out := new(resources.RegisterResponse)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUser/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserClient) Info(ctx context.Context, in *resources.InfoRequest, opts ...grpc.CallOption) (*resources.Info, error) {
	out := new(resources.Info)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUser/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserClient) ChangePassword(ctx context.Context, in *resources.ChangePasswordRequest, opts ...grpc.CallOption) (*resources.ChangePasswordResponse, error) {
	out := new(resources.ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUser/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserClient) ChangeAvatar(ctx context.Context, in *resources.ChangeAvatarRequest, opts ...grpc.CallOption) (*resources.ChangeAvatarResponse, error) {
	out := new(resources.ChangeAvatarResponse)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUser/ChangeAvatar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserClient) ChangeMobile(ctx context.Context, in *resources.ChangeMobileRequest, opts ...grpc.CallOption) (*resources.ChangeMobileResponse, error) {
	out := new(resources.ChangeMobileResponse)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUser/ChangeMobile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserClient) ChangeEmail(ctx context.Context, in *resources.ChangeEmailRequest, opts ...grpc.CallOption) (*resources.ChangeEmailResponse, error) {
	out := new(resources.ChangeEmailResponse)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUser/ChangeEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserClient) ChangeNickname(ctx context.Context, in *resources.ChangeNicknameRequest, opts ...grpc.CallOption) (*resources.ChangeNicknameResponse, error) {
	out := new(resources.ChangeNicknameResponse)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUser/ChangeNickname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserClient) ChangeSex(ctx context.Context, in *resources.ChangeSexRequest, opts ...grpc.CallOption) (*resources.ChangeSexResponse, error) {
	out := new(resources.ChangeSexResponse)
	err := c.cc.Invoke(ctx, "/user.api.user.userservicev1.SrvUser/ChangeSex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvUserServer is the server API for SrvUser service.
// All implementations must embed UnimplementedSrvUserServer
// for forward compatibility
type SrvUserServer interface {
	// Login 用户登录
	Login(context.Context, *resources.LoginRequest) (*resources.LoginResponse, error)
	// Register 用户注册
	Register(context.Context, *resources.RegisterRequest) (*resources.RegisterResponse, error)
	// Info 用户信息
	Info(context.Context, *resources.InfoRequest) (*resources.Info, error)
	// ChangePassword 用户修改密码
	ChangePassword(context.Context, *resources.ChangePasswordRequest) (*resources.ChangePasswordResponse, error)
	// ChangeAvatar 用户修改头像
	ChangeAvatar(context.Context, *resources.ChangeAvatarRequest) (*resources.ChangeAvatarResponse, error)
	// ChangeMobile 用户修改手机号
	ChangeMobile(context.Context, *resources.ChangeMobileRequest) (*resources.ChangeMobileResponse, error)
	// ChangeEmail 用户修改邮箱
	ChangeEmail(context.Context, *resources.ChangeEmailRequest) (*resources.ChangeEmailResponse, error)
	// ChangeNickname 用户修改昵称
	ChangeNickname(context.Context, *resources.ChangeNicknameRequest) (*resources.ChangeNicknameResponse, error)
	// ChangeSex 用户修改性别
	ChangeSex(context.Context, *resources.ChangeSexRequest) (*resources.ChangeSexResponse, error)
	mustEmbedUnimplementedSrvUserServer()
}

// UnimplementedSrvUserServer must be embedded to have forward compatible implementations.
type UnimplementedSrvUserServer struct {
}

func (UnimplementedSrvUserServer) Login(context.Context, *resources.LoginRequest) (*resources.LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedSrvUserServer) Register(context.Context, *resources.RegisterRequest) (*resources.RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedSrvUserServer) Info(context.Context, *resources.InfoRequest) (*resources.Info, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedSrvUserServer) ChangePassword(context.Context, *resources.ChangePasswordRequest) (*resources.ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedSrvUserServer) ChangeAvatar(context.Context, *resources.ChangeAvatarRequest) (*resources.ChangeAvatarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeAvatar not implemented")
}
func (UnimplementedSrvUserServer) ChangeMobile(context.Context, *resources.ChangeMobileRequest) (*resources.ChangeMobileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeMobile not implemented")
}
func (UnimplementedSrvUserServer) ChangeEmail(context.Context, *resources.ChangeEmailRequest) (*resources.ChangeEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeEmail not implemented")
}
func (UnimplementedSrvUserServer) ChangeNickname(context.Context, *resources.ChangeNicknameRequest) (*resources.ChangeNicknameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeNickname not implemented")
}
func (UnimplementedSrvUserServer) ChangeSex(context.Context, *resources.ChangeSexRequest) (*resources.ChangeSexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeSex not implemented")
}
func (UnimplementedSrvUserServer) mustEmbedUnimplementedSrvUserServer() {}

// UnsafeSrvUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvUserServer will
// result in compilation errors.
type UnsafeSrvUserServer interface {
	mustEmbedUnimplementedSrvUserServer()
}

func RegisterSrvUserServer(s grpc.ServiceRegistrar, srv SrvUserServer) {
	s.RegisterService(&SrvUser_ServiceDesc, srv)
}

func _SrvUser_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUser/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserServer).Login(ctx, req.(*resources.LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUser_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUser/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserServer).Register(ctx, req.(*resources.RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUser_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUser/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserServer).Info(ctx, req.(*resources.InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUser_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUser/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserServer).ChangePassword(ctx, req.(*resources.ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUser_ChangeAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.ChangeAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserServer).ChangeAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUser/ChangeAvatar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserServer).ChangeAvatar(ctx, req.(*resources.ChangeAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUser_ChangeMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.ChangeMobileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserServer).ChangeMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUser/ChangeMobile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserServer).ChangeMobile(ctx, req.(*resources.ChangeMobileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUser_ChangeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.ChangeEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserServer).ChangeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUser/ChangeEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserServer).ChangeEmail(ctx, req.(*resources.ChangeEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUser_ChangeNickname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.ChangeNicknameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserServer).ChangeNickname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUser/ChangeNickname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserServer).ChangeNickname(ctx, req.(*resources.ChangeNicknameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUser_ChangeSex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.ChangeSexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserServer).ChangeSex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.user.userservicev1.SrvUser/ChangeSex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserServer).ChangeSex(ctx, req.(*resources.ChangeSexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SrvUser_ServiceDesc is the grpc.ServiceDesc for SrvUser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvUser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.api.user.userservicev1.SrvUser",
	HandlerType: (*SrvUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _SrvUser_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _SrvUser_Register_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _SrvUser_Info_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _SrvUser_ChangePassword_Handler,
		},
		{
			MethodName: "ChangeAvatar",
			Handler:    _SrvUser_ChangeAvatar_Handler,
		},
		{
			MethodName: "ChangeMobile",
			Handler:    _SrvUser_ChangeMobile_Handler,
		},
		{
			MethodName: "ChangeEmail",
			Handler:    _SrvUser_ChangeEmail_Handler,
		},
		{
			MethodName: "ChangeNickname",
			Handler:    _SrvUser_ChangeNickname_Handler,
		},
		{
			MethodName: "ChangeSex",
			Handler:    _SrvUser_ChangeSex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/v1/services/user.service.v1.proto",
}
